---
version: 3

images:
  base_image:
    name: quay.io/centos/centos:stream9

dependencies:
  galaxy: requirements.yml
  python: requirements.txt
  system: bindep.txt
  python_interpreter:
    package_system: python39
    python_path: /usr/bin/python3.9
  ansible_core:
    package_pip: ansible-core==2.14.0
  ansible_runner:
    package_pip: ansible-runner==2.3.2

additional_build_steps:
  prepend_base: |
    RUN whoami
    RUN cat /etc/os-release
  append_base:
    - RUN echo This is a post-install command!
    - RUN ls -la /etc
